name: D3C
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas
  - geopandas
  - numpy=1.23
  - pip
  - shapely
  - bs4
  - time
  - requests
  - contextily
  - selenium
  - webdriver-manager
  - pip:
    - matplotlib
    - seaborn==0.12.0
    - geopandas
    - shapely